version: '3'

services:
  app:
    build: .
    entrypoint: /bin/sh
    command:
      - "-c"
      - "ENDPOINT=$$UFFIZZI_URL node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 8080

  continuous_preview:
    share_to_github: true
    delete_preview_after: 6h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
